### PR TITLE
Use `return PyErr_NoMemory()` for _new function when error

### PR DESCRIPTION
**Pull request by miurahr**
When there is no memory and fails on `tp_alloc()` , `*_new()` function might return NULL without error type.
This patch fixes the behavior.

### CODE REVIEW

**Comment by animalize** [comment]
The default function of `tp_alloc` is `PyType_GenericAlloc()`, it sets the `MemoryError`.
https://github.com/python/cpython/blob/v3.5.0/Objects/typeobject.c#L945-L946

Whenever in doubt, I check the source code of Python.
If accept this PR, `PyErr_NoMemory()` will be executed twice, so I close this PR.

**Comment by animalize** [comment]
I used to spend time checking such details, and manually triggering exceptions to see if them can be handled correctly.

Once the development of pyzstd module is completed, almost no maintenance is needed.
Basically just update the zstd source code, and use new API in major version update.

**Comment by animalize** [comment]
Searching `type->tp_alloc` in Python source code,  the code use the same style.

**Comment by miurahr** [comment]
Thank you for the explanation.

**Pull request closed without merging**
